# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0ecacdf3baecdb7b9a6c59f6e5c98752c4eb5491457dff2caaf12c47810b667b86f951d31d3c2319c3d49a7096dc61766d1e85ffc5e898280d4e521e2f312b

test:
  secret_key_base: 3df14332f8c307f16b517bd7264b16d6c646f274d335b29183ecf2a402ed6a65d98eef05069753c1a8e05ea679731b4e15e61f59704735aaf2ec0aba1917a927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
